apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamingapp.fullname" . }}-streaming
  labels:
    app: {{ include "streamingapp.name" . }}
    component: streaming
spec:
  type: ClusterIP
  selector:
    app: {{ include "streamingapp.name" . }}
    component: streaming
  ports:
    - name: http
      port: {{ .Values.service.streaming.port }}
      targetPort: {{ .Values.service.streaming.targetPort }}
      protocol: TCP
